### ISSUE TITLE
Can I use telegram mtproto proxies as a windows vpn?

### ISSUE THREAD

**Issue by ababayi** [Oct4Pie/MtProto-ngrok#2]
Hello guys,
I live in Iran, there are many internet limitation but fortunately telegram mtporo proxies work well.
Is there any way to use this proxies for all applications such as web-browsers, games, ....?

**Comment by Oct4Pie** [comment]
Hello,
That's a question I had before. Well, unfortunately, MTProto is a protocol designed specifically for Telegram.
However, I think that you have seen how Telegram preloads pictures, media, and websites. It does that by using a transport layer (mostly HTTP). Therefore, building a tunnel that could be used for other apps is possible but doesn't seem very effective due to the heavy encryption mechanism. I will still look into it though and see how it turns out.
